# Generated by Django 2.2.3 on 2020-02-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_User',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='swuapp.Student_User'),
        ),
        migrations.AlterField(
            model_name='userlecture',
            name='myuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='myuserid', serialize=False, to='swuapp.Student_User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
