# Generated by Django 2.2.3 on 2020-02-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swuapp', '0002_auto_20200224_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlecture',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlecture',
            name='myuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myuserid', to='swuapp.Student_User'),
        ),
    ]
