# Generated by Django 3.0.3 on 2020-02-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swuapp', '0003_auto_20200224_1325'),
        ('swuapp', '0002_auto_20200224_0312'),
    ]

    operations = [
    ]
